#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 15 14:53:01 2024

@author: fatihaltun
"""

import sys
sys.path.insert(0, '/usr/share/pardus/pardus-power-manager/src/')
import Main

